# Generated by Django 6.0.4 on 2026-04-18 09:17

import catalog.models
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _category_id_for_name(name: str) -> str:
    normalized = (name or '').strip()
    if normalized.lower() == 'printers':
        return 'c1'
    if normalized.lower() == 'accessories':
        return 'c2'
    return f"cat_{uuid.uuid5(uuid.NAMESPACE_DNS, normalized).hex[:28]}"


def forwards_convert_category_values(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    Product = apps.get_model('catalog', 'Product')
    SellerProduct = apps.get_model('catalog', 'SellerProduct')

    raw_values = set(
        value
        for value in Product.objects.values_list('category', flat=True)
        if isinstance(value, str) and value.strip()
    )
    raw_values.update(
        value
        for value in SellerProduct.objects.values_list('category', flat=True)
        if isinstance(value, str) and value.strip()
    )

    for raw_name in raw_values:
        category_name = raw_name.strip()
        category_id = _category_id_for_name(category_name)
        Category.objects.update_or_create(
            id=category_id,
            defaults={'name': category_name},
        )
        Product.objects.filter(category=raw_name).update(category=category_id)
        SellerProduct.objects.filter(category=raw_name).update(category=category_id)


def backwards_restore_category_names(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    Product = apps.get_model('catalog', 'Product')
    SellerProduct = apps.get_model('catalog', 'SellerProduct')

    for category in Category.objects.all().only('id', 'name'):
        Product.objects.filter(category=category.id).update(category=category.name)
        SellerProduct.objects.filter(category=category.id).update(category=category.name)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_image_upload_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=catalog.models.generate_string_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(
            forwards_convert_category_values,
            backwards_restore_category_names,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_products', to='catalog.category'),
        ),
    ]
