# Generated by Django 6.0.4 on 2026-05-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Brand New'), ('used', 'Used')], default='new', max_length=12),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='condition',
            field=models.CharField(choices=[('new', 'Brand New'), ('used', 'Used')], default='new', max_length=12),
        ),
    ]
