# Generated by Django 5.2.13 on 2026-08-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_sellerproduct_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot_deal',
            field=models.BooleanField(default=False),
        ),
    ]
