# Generated by Django 6.0.4 on 2026-04-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_address', models.CharField(blank=True, max_length=255)),
                ('business_hours', models.CharField(blank=True, max_length=120)),
                ('tiktok_url', models.URLField(blank=True)),
                ('map_url', models.URLField(blank=True)),
                ('hero_tagline', models.CharField(blank=True, max_length=255)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_description', models.TextField(blank=True)),
                ('about_title', models.CharField(blank=True, max_length=255)),
                ('about_description', models.TextField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=18)),
                ('students_trained', models.PositiveIntegerField(default=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
