# Generated by Django 5.2.13 on 2026-07-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
