# Generated by Django 6.0.4 on 2026-04-18 12:48

import django.utils.timezone
import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationdevice_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.CharField(default=notifications.models.generate_string_id, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationdevice',
            name='id',
            field=models.CharField(default=notifications.models.generate_string_id, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationdevice',
            name='last_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
