# Generated by Django 6.0.4 on 2026-04-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_id_alter_notificationdevice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('stock_low', 'Stock Low'), ('stock_out', 'Stock Out'), ('seller_registered', 'Seller Registered'), ('reservation_created', 'Reservation Created'), ('reservation_approved', 'Reservation Approved'), ('reservation_rejected', 'Reservation Rejected'), ('reservation_delivered', 'Reservation Delivered')], max_length=40),
        ),
    ]
