# Generated by Django 5.2.13 on 2026-08-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('stock_low', 'Stock Low'), ('stock_out', 'Stock Out'), ('seller_registered', 'Seller Registered'), ('seller_product_submitted', 'Seller Product Submitted'), ('seller_product_approved', 'Seller Product Approved'), ('seller_product_rejected', 'Seller Product Rejected'), ('seller_product_unavailable', 'Seller Product Unavailable'), ('reservation_created', 'Reservation Created'), ('reservation_approved', 'Reservation Approved'), ('reservation_rejected', 'Reservation Rejected'), ('reservation_delivered', 'Reservation Delivered')], max_length=40),
        ),
    ]
